
export const jobTitles = [
  "Accountant",
  "Actuary",
  "Administrative Assistant", 
  "Advertising Manager",
  "Aerospace Engineer",
  "Agricultural Engineer",
  "Air Traffic Controller",
  "Animator",
  "Architect",
  "Art Director",
  "Artificial Intelligence Engineer",
  "Athletic Trainer",
  "Audiologist",
  "Automotive Mechanic",
  "Biomedical Engineer",
  "Budget Analyst",
  "Business Analyst",
  "Cartographer",
  "Chemical Engineer",
  "Chief Executive Officer (CEO)",
  "Civil Engineer",
  "Clinical Psychologist",
  "Computer Hardware Engineer",
  "Computer Network Architect",
  "Computer Programmer",
  "Computer Systems Analyst",
  "Construction Manager",
  "Content Writer",
  "Customer Service Representative",
  "Data Analyst",
  "Data Scientist",
  "Database Administrator",
  "Dental Hygienist",
  "Dentist",
  "Dietitian",
  "Economist",
  "Electrical Engineer",
  "Elementary School Teacher",
  "Environmental Engineer",
  "Environmental Scientist",
  "Event Planner",
  "Financial Advisor",
  "Financial Analyst",
  "Financial Manager",
  "Flight Attendant",
  "Forensic Science Technician",
  "Graphic Designer",
  "Health Information Technician",
  "Human Resources Manager",
  "Industrial Designer",
  "Information Security Analyst",
  "Interior Designer",
  "Interpreter/Translator",
  "IT Project Manager",
  "Landscape Architect",
  "Lawyer",
  "Librarian",
  "Loan Officer",
  "Logistician",
  "Market Research Analyst",
  "Marketing Manager",
  "Mechanical Engineer",
  "Medical Assistant",
  "Medical Laboratory Technician",
  "Medical Records Technician",
  "Meeting/Event Planner",
  "Microbiologist",
  "Middle School Teacher",
  "Network Administrator",
  "Nuclear Engineer",
  "Nurse Practitioner",
  "Occupational Therapist",
  "Operations Research Analyst",
  "Optometrist",
  "Orthodontist",
  "Paramedic",
  "Petroleum Engineer",
  "Pharmacist",
  "Physical Therapist",
  "Physician",
  "Physician Assistant",
  "Pilot",
  "Police Officer",
  "Political Scientist",
  "Product Manager",
  "Project Manager",
  "Psychologist",
  "Public Relations Specialist",
  "Radiologic Technologist",
  "Real Estate Agent",
  "Registered Nurse",
  "Research Scientist",
  "Restaurant Manager",
  "Sales Manager",
  "School Counselor",
  "Social Media Manager",
  "Social Worker",
  "Software Developer",
  "Software Engineer",
  "Solar Photovoltaic Installer",
  "Speech-Language Pathologist",
  "Statistician",
  "Systems Analyst",
  "Tax Accountant",
  "Technical Writer",
  "UX Designer",
  "Veterinarian",
  "Web Developer",
  "Wind Turbine Technician"
];

export const filterJobTitles = (input: string): string[] => {
  if (!input || input.length < 2) return [];
  
  const lowerCaseInput = input.toLowerCase();
  return jobTitles
    .filter(title => title.toLowerCase().includes(lowerCaseInput))
    .slice(0, 5); // Limit to 5 results
};
