// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szobkfhxqvhvkiqxeabe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6b2JrZmh4cXZodmtpcXhlYWJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNjg0MzEsImV4cCI6MjA1OTY0NDQzMX0.BVSuUPFuk9CYKh30DOE5z4gUwwN54MdcnAMSEL-aVKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);